/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Winter.glb -o src/components/Winter.jsx -k -K -r public 
*/
import { Html, useGLTF } from "@react-three/drei";
import { useAtom } from "jotai";
import React from "react";
import { degToRad } from "three/src/math/MathUtils";
import { currentPageAtom } from "./UI";

const OverlayItem = ({
  className = "",
  title,
  description,
  button,
  bgColor,
  ...props
}) => {
  const [currentPage] = useAtom(currentPageAtom);
  return (
    <Html
      transform
      distanceFactor={1.2}
      center
      className={`w-64 rounded-md overflow-hidden ${
        currentPage === "store" ? "" : "opacity-0"
      } transition-opacity duration-1000 ${className}`}
      {...props}
    >
      {/* <div className="bg-white backdrop-blur-lg text-lg p-2 w-full hover:opacity-100 opacity-70">
        <h2 className="font-bold">{title}</h2>
        <p>{description}</p>
      </div> */}
      <button
        className={`${bgColor} hover:bg-black transition-colors duration-500 px-4 py-2 font-bold text-white w-full text-lg`}
      >
        {button}
      </button>
    </Html>
  );
};

export function Winter({ html, ...props }) {
  const { nodes, materials } = useGLTF('/models/Winter.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="group15097131" geometry={nodes.group15097131.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group41684049" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh41684049" geometry={nodes.mesh41684049.geometry} material={materials.mat9} />
          <mesh name="mesh41684049_1" geometry={nodes.mesh41684049_1.geometry} material={materials.mat21} />
          <mesh name="mesh41684049_2" geometry={nodes.mesh41684049_2.geometry} material={materials.mat20} />
        </group>
        <mesh name="group49712894" geometry={nodes.group49712894.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group50491792" geometry={nodes.group50491792.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group51859945" geometry={nodes.group51859945.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group57927599" geometry={nodes.group57927599.geometry} material={materials.mat13} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group60572757" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh60572757" geometry={nodes.mesh60572757.geometry} material={materials.mat21} />
          <mesh name="mesh60572757_1" geometry={nodes.mesh60572757_1.geometry} material={materials.mat22} />
        </group>
        <mesh name="group80496673" geometry={nodes.group80496673.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group82190946" geometry={nodes.group82190946.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group97955469" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh97955469" geometry={nodes.mesh97955469.geometry} material={materials.mat17} />
          <mesh name="mesh97955469_1" geometry={nodes.mesh97955469_1.geometry} material={materials.mat20} />
        </group>
        <group name="group113738511" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh113738511" geometry={nodes.mesh113738511.geometry} material={materials.mat21} />
          <mesh name="mesh113738511_1" geometry={nodes.mesh113738511_1.geometry} material={materials.mat22} />
        </group>
        <mesh name="group124819790" geometry={nodes.group124819790.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group128096956" geometry={nodes.group128096956.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group130787562" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh130787562" geometry={nodes.mesh130787562.geometry} material={materials.mat20} />
          <mesh name="mesh130787562_1" geometry={nodes.mesh130787562_1.geometry} material={materials.mat17} />
        </group>
        <mesh name="group160047057" geometry={nodes.group160047057.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group168950952" geometry={nodes.group168950952.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group181415355" geometry={nodes.group181415355.geometry} material={materials.mat15} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group198768325" geometry={nodes.group198768325.geometry} material={materials.mat22} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group202553836" geometry={nodes.group202553836.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group202666273" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh202666273" geometry={nodes.mesh202666273.geometry} material={materials.mat23} />
          <mesh name="mesh202666273_1" geometry={nodes.mesh202666273_1.geometry} material={materials.mat12} />
        </group>
        <mesh name="group211210989" geometry={nodes.group211210989.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group218393834" geometry={nodes.group218393834.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group251340485" geometry={nodes.group251340485.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group252869350" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh252869350" geometry={nodes.mesh252869350.geometry} material={materials.mat10} />
          <mesh name="mesh252869350_1" geometry={nodes.mesh252869350_1.geometry} material={materials.mat21} />
        </group>
        <mesh name="group256627188" geometry={nodes.group256627188.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group268262754" geometry={nodes.group268262754.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group282870480" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh282870480" geometry={nodes.mesh282870480.geometry} material={materials.mat10} />
          <mesh name="mesh282870480_1" geometry={nodes.mesh282870480_1.geometry} material={materials.mat21} />
        </group>
        <mesh name="group291988410" geometry={nodes.group291988410.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group302630071" geometry={nodes.group302630071.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group328412582" geometry={nodes.group328412582.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group336174369" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh336174369" geometry={nodes.mesh336174369.geometry} material={materials.mat13} />
          <mesh name="mesh336174369_1" geometry={nodes.mesh336174369_1.geometry} material={materials.mat21} />
          <mesh name="mesh336174369_2" geometry={nodes.mesh336174369_2.geometry} material={materials.mat20} />
        </group>
        <mesh name="group338925138" geometry={nodes.group338925138.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group371915815" geometry={nodes.group371915815.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group372838791" geometry={nodes.group372838791.geometry} material={materials.mat22} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group385889537" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh385889537" geometry={nodes.mesh385889537.geometry} material={materials.mat23} />
          <mesh name="mesh385889537_1" geometry={nodes.mesh385889537_1.geometry} material={materials.mat21} />
          <mesh name="mesh385889537_2" geometry={nodes.mesh385889537_2.geometry} material={materials.mat13} />
          <mesh name="mesh385889537_3" geometry={nodes.mesh385889537_3.geometry} material={materials.mat20} />
          <mesh name="mesh385889537_4" geometry={nodes.mesh385889537_4.geometry} material={materials.mat12} />
        </group>
        <mesh name="group411471375" geometry={nodes.group411471375.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group418701819" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh418701819" geometry={nodes.mesh418701819.geometry} material={materials.mat21} />
          <mesh name="mesh418701819_1" geometry={nodes.mesh418701819_1.geometry} material={materials.mat22} />
        </group>
        <group name="group421275877" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh421275877" geometry={nodes.mesh421275877.geometry} material={materials.mat12} />
          <mesh name="mesh421275877_1" geometry={nodes.mesh421275877_1.geometry} material={materials.mat13} />
          <mesh name="mesh421275877_2" geometry={nodes.mesh421275877_2.geometry} material={materials.mat21} />
          <mesh name="mesh421275877_3" geometry={nodes.mesh421275877_3.geometry} material={materials.mat22} />
          <mesh name="mesh421275877_4" geometry={nodes.mesh421275877_4.geometry} material={materials.mat23} />
          <mesh name="mesh421275877_5" geometry={nodes.mesh421275877_5.geometry} material={materials.mat17} />
          <mesh name="mesh421275877_6" geometry={nodes.mesh421275877_6.geometry} material={materials.mat15} />
        </group>
        <mesh name="group428826019" geometry={nodes.group428826019.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group440894978" geometry={nodes.group440894978.geometry} material={materials.mat23} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group450603092" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh450603092" geometry={nodes.mesh450603092.geometry} material={materials.mat22} />
          <mesh name="mesh450603092_1" geometry={nodes.mesh450603092_1.geometry} material={materials.mat21} />
        </group>
        <mesh name="group460370094" geometry={nodes.group460370094.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group475441814" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh475441814" geometry={nodes.mesh475441814.geometry} material={materials.mat18} />
          <mesh name="mesh475441814_1" geometry={nodes.mesh475441814_1.geometry} material={materials.mat20} />
        </group>
        <mesh name="group476825986" geometry={nodes.group476825986.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group497574678" geometry={nodes.group497574678.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group499692950" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh499692950" geometry={nodes.mesh499692950.geometry} material={materials.mat13} />
          <mesh name="mesh499692950_1" geometry={nodes.mesh499692950_1.geometry} material={materials.mat21} />
          <mesh name="mesh499692950_2" geometry={nodes.mesh499692950_2.geometry} material={materials.mat20} />
        </group>
        <group name="group507024131" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh507024131" geometry={nodes.mesh507024131.geometry} material={materials.mat16} />
          <mesh name="mesh507024131_1" geometry={nodes.mesh507024131_1.geometry} material={materials.mat15} />
        </group>
        <mesh name="group541932812" geometry={nodes.group541932812.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group577470802" geometry={nodes.group577470802.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group578989476" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh578989476" geometry={nodes.mesh578989476.geometry} material={materials.mat19} />
          <mesh name="mesh578989476_1" geometry={nodes.mesh578989476_1.geometry} material={materials.mat21} />
          <mesh name="mesh578989476_2" geometry={nodes.mesh578989476_2.geometry} material={materials.mat23} />
          <mesh name="mesh578989476_3" geometry={nodes.mesh578989476_3.geometry} material={materials.mat12} />
        </group>
        <mesh name="group579536226" geometry={nodes.group579536226.geometry} material={materials.mat17} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group589269863" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh589269863" geometry={nodes.mesh589269863.geometry} material={materials.mat20} />
          <mesh name="mesh589269863_1" geometry={nodes.mesh589269863_1.geometry} material={materials.mat21} />
          <mesh name="mesh589269863_2" geometry={nodes.mesh589269863_2.geometry} material={materials.mat9} />
        </group>
        <mesh name="group592178080" geometry={nodes.group592178080.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group618769167" geometry={nodes.group618769167.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group622706014" geometry={nodes.group622706014.geometry} material={materials.mat17} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group626367625" geometry={nodes.group626367625.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group627366875" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh627366875" geometry={nodes.mesh627366875.geometry} material={materials.mat23} />
          <mesh name="mesh627366875_1" geometry={nodes.mesh627366875_1.geometry} material={materials.mat12} />
        </group>
        <mesh name="group654874048" geometry={nodes.group654874048.geometry} material={materials.mat17} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group671192930" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh671192930" geometry={nodes.mesh671192930.geometry} material={materials.mat20} />
          <mesh name="mesh671192930_1" geometry={nodes.mesh671192930_1.geometry} material={materials.mat21} />
          <mesh name="mesh671192930_2" geometry={nodes.mesh671192930_2.geometry} material={materials.mat13} />
        </group>
        <mesh name="group686117475" geometry={nodes.group686117475.geometry} material={materials.mat13} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group689309211" geometry={nodes.group689309211.geometry} material={materials.mat23} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group690363291" geometry={nodes.group690363291.geometry} material={materials.mat13} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group691372555" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh691372555" geometry={nodes.mesh691372555.geometry} material={materials.mat22} />
          <mesh name="mesh691372555_1" geometry={nodes.mesh691372555_1.geometry} material={materials.mat21} />
        </group>
        <group name="group702838795" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh702838795" geometry={nodes.mesh702838795.geometry} material={materials.mat22} />
          <mesh name="mesh702838795_1" geometry={nodes.mesh702838795_1.geometry} material={materials.mat21} />
        </group>
        <group name="group745656281" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh745656281" geometry={nodes.mesh745656281.geometry} material={materials.mat12} />
          <mesh name="mesh745656281_1" geometry={nodes.mesh745656281_1.geometry} material={materials.mat13} />
          <mesh name="mesh745656281_2" geometry={nodes.mesh745656281_2.geometry} material={materials.mat21} />
          <mesh name="mesh745656281_3" geometry={nodes.mesh745656281_3.geometry} material={materials.mat22} />
          <mesh name="mesh745656281_4" geometry={nodes.mesh745656281_4.geometry} material={materials.mat23} />
        </group>
        <mesh name="group777932778" geometry={nodes.group777932778.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group781646145" geometry={nodes.group781646145.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group794915969" geometry={nodes.group794915969.geometry} material={materials.mat17} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group796667337" geometry={nodes.group796667337.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group806799290" geometry={nodes.group806799290.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group817009042" geometry={nodes.group817009042.geometry} material={materials.mat22} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group821600289" geometry={nodes.group821600289.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group828510215" geometry={nodes.group828510215.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group840611071" geometry={nodes.group840611071.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group881312660" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh881312660" geometry={nodes.mesh881312660.geometry} material={materials.mat16} />
          <mesh name="mesh881312660_1" geometry={nodes.mesh881312660_1.geometry} material={materials.mat4} />
          <mesh name="mesh881312660_2" geometry={nodes.mesh881312660_2.geometry} material={materials.mat5} />
          <mesh name="mesh881312660_3" geometry={nodes.mesh881312660_3.geometry} material={materials.mat15} />
          <mesh name="mesh881312660_4" geometry={nodes.mesh881312660_4.geometry} material={materials.mat23} />
          <mesh name="mesh881312660_5" geometry={nodes.mesh881312660_5.geometry} material={materials.mat12} />
          <mesh name="mesh881312660_6" geometry={nodes.mesh881312660_6.geometry} material={materials.mat22} />
        </group>
        <mesh name="group881904468" geometry={nodes.group881904468.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group903730392" geometry={nodes.group903730392.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group906360025" geometry={nodes.group906360025.geometry} material={materials.mat17} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group917550991" geometry={nodes.group917550991.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group917967987" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh917967987" geometry={nodes.mesh917967987.geometry} material={materials.mat20} />
          <mesh name="mesh917967987_1" geometry={nodes.mesh917967987_1.geometry} material={materials.mat21} />
          <mesh name="mesh917967987_2" geometry={nodes.mesh917967987_2.geometry} material={materials.mat9} />
        </group>
        <mesh name="group926383226" geometry={nodes.group926383226.geometry} material={materials.mat9} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group935236113" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh935236113" geometry={nodes.mesh935236113.geometry} material={materials.mat20} />
          <mesh name="mesh935236113_1" geometry={nodes.mesh935236113_1.geometry} material={materials.mat17} />
        </group>
        <mesh name="group935343989" geometry={nodes.group935343989.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group976712999" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh976712999" geometry={nodes.mesh976712999.geometry} material={materials.mat20} />
          <mesh name="mesh976712999_1" geometry={nodes.mesh976712999_1.geometry} material={materials.mat13} />
          <mesh name="mesh976712999_2" geometry={nodes.mesh976712999_2.geometry} material={materials.mat21} />
        </group>
        <mesh name="group980274275" geometry={nodes.group980274275.geometry} material={materials.mat17} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group990275946" geometry={nodes.group990275946.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1011134261" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1011134261" geometry={nodes.mesh1011134261.geometry} material={materials.mat10} />
          <mesh name="mesh1011134261_1" geometry={nodes.mesh1011134261_1.geometry} material={materials.mat21} />
        </group>
        <mesh name="group1016711687" geometry={nodes.group1016711687.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1029433171" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1029433171" geometry={nodes.mesh1029433171.geometry} material={materials.mat23} />
          <mesh name="mesh1029433171_1" geometry={nodes.mesh1029433171_1.geometry} material={materials.mat22} />
        </group>
        <mesh name="group1072235988" geometry={nodes.group1072235988.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1075244269" geometry={nodes.group1075244269.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1081022780" geometry={nodes.group1081022780.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1084115125" geometry={nodes.group1084115125.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1087780685" geometry={nodes.group1087780685.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1087985354" geometry={nodes.group1087985354.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1102352616" geometry={nodes.group1102352616.geometry} material={materials.mat22} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1102504741" geometry={nodes.group1102504741.geometry} material={materials.mat17} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1106803793" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1106803793" geometry={nodes.mesh1106803793.geometry} material={materials.mat12} />
          <mesh name="mesh1106803793_1" geometry={nodes.mesh1106803793_1.geometry} material={materials.mat21} />
          <mesh name="mesh1106803793_2" geometry={nodes.mesh1106803793_2.geometry} material={materials.mat19} />
          <mesh name="mesh1106803793_3" geometry={nodes.mesh1106803793_3.geometry} material={materials.mat23} />
        </group>
        <group name="group1112086536" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1112086536" geometry={nodes.mesh1112086536.geometry} material={materials.mat21} />
          <mesh name="mesh1112086536_1" geometry={nodes.mesh1112086536_1.geometry} material={materials.mat20} />
          <mesh name="mesh1112086536_2" geometry={nodes.mesh1112086536_2.geometry} material={materials.mat9} />
        </group>
        <group name="group1112412566" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1112412566" geometry={nodes.mesh1112412566.geometry} material={materials.mat21} />
          <mesh name="mesh1112412566_1" geometry={nodes.mesh1112412566_1.geometry} material={materials.mat17} />
        </group>
        <mesh name="group1115087124" geometry={nodes.group1115087124.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1122560806" geometry={nodes.group1122560806.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1130814559" geometry={nodes.group1130814559.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1150916338" geometry={nodes.group1150916338.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1166666576" geometry={nodes.group1166666576.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1174240669" geometry={nodes.group1174240669.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1177153970" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1177153970" geometry={nodes.mesh1177153970.geometry} material={materials.mat21} />
          <mesh name="mesh1177153970_1" geometry={nodes.mesh1177153970_1.geometry} material={materials.mat10} />
        </group>
        <group name="group1185948190" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1185948190" geometry={nodes.mesh1185948190.geometry} material={materials.mat20} />
          <mesh name="mesh1185948190_1" geometry={nodes.mesh1185948190_1.geometry} material={materials.mat17} />
        </group>
        <group name="group1190056241" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1190056241" geometry={nodes.mesh1190056241.geometry} material={materials.mat21} />
          <mesh name="mesh1190056241_1" geometry={nodes.mesh1190056241_1.geometry} material={materials.mat22} />
        </group>
        <mesh name="group1199516310" geometry={nodes.group1199516310.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1208923874" geometry={nodes.group1208923874.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1246110135" geometry={nodes.group1246110135.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1249699877" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1249699877" geometry={nodes.mesh1249699877.geometry} material={materials.mat22} />
          <mesh name="mesh1249699877_1" geometry={nodes.mesh1249699877_1.geometry} material={materials.mat21} />
        </group>
        <mesh name="group1255605153" geometry={nodes.group1255605153.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1263281357" geometry={nodes.group1263281357.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1265164841" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1265164841" geometry={nodes.mesh1265164841.geometry} material={materials.mat17} />
          <mesh name="mesh1265164841_1" geometry={nodes.mesh1265164841_1.geometry} material={materials.mat20} />
        </group>
        <group name="group1283122326" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1283122326" geometry={nodes.mesh1283122326.geometry} material={materials.mat20} />
          <mesh name="mesh1283122326_1" geometry={nodes.mesh1283122326_1.geometry} material={materials.mat18} />
        </group>
        <mesh name="group1335324189" geometry={nodes.group1335324189.geometry} material={materials.mat17} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1336022506" geometry={nodes.group1336022506.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1369651604" geometry={nodes.group1369651604.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1378943151" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1378943151" geometry={nodes.mesh1378943151.geometry} material={materials.mat21} />
          <mesh name="mesh1378943151_1" geometry={nodes.mesh1378943151_1.geometry} material={materials.mat9} />
          <mesh name="mesh1378943151_2" geometry={nodes.mesh1378943151_2.geometry} material={materials.mat20} />
        </group>
        <group name="group1412951148" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1412951148" geometry={nodes.mesh1412951148.geometry} material={materials.mat21} />
          <mesh name="mesh1412951148_1" geometry={nodes.mesh1412951148_1.geometry} material={materials.mat22} />
          <mesh name="mesh1412951148_2" geometry={nodes.mesh1412951148_2.geometry} material={materials.mat15} />
          <mesh name="mesh1412951148_3" geometry={nodes.mesh1412951148_3.geometry} material={materials.mat23} />
          <mesh name="mesh1412951148_4" geometry={nodes.mesh1412951148_4.geometry} material={materials.mat13} />
          <mesh name="mesh1412951148_5" geometry={nodes.mesh1412951148_5.geometry} material={materials.mat20} />
        </group>
        <mesh name="group1422634930" geometry={nodes.group1422634930.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1425010795" geometry={nodes.group1425010795.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1433216486" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1433216486" geometry={nodes.mesh1433216486.geometry} material={materials.mat21} />
          <mesh name="mesh1433216486_1" geometry={nodes.mesh1433216486_1.geometry} material={materials.mat22} />
        </group>
        <mesh name="group1455600834" geometry={nodes.group1455600834.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1458665551" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1458665551" geometry={nodes.mesh1458665551.geometry} material={materials.mat21} />
          <mesh name="mesh1458665551_1" geometry={nodes.mesh1458665551_1.geometry} material={materials.mat22} />
        </group>
        <mesh name="group1466681090" geometry={nodes.group1466681090.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1485499779" geometry={nodes.group1485499779.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1498486265" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1498486265" geometry={nodes.mesh1498486265.geometry} material={materials.mat21} />
          <mesh name="mesh1498486265_1" geometry={nodes.mesh1498486265_1.geometry} material={materials.mat22} />
        </group>
        <mesh name="group1538221661" geometry={nodes.group1538221661.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1587275435" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1587275435" geometry={nodes.mesh1587275435.geometry} material={materials.mat13} />
          <mesh name="mesh1587275435_1" geometry={nodes.mesh1587275435_1.geometry} material={materials.mat21} />
          <mesh name="mesh1587275435_2" geometry={nodes.mesh1587275435_2.geometry} material={materials.mat22} />
          <mesh name="mesh1587275435_3" geometry={nodes.mesh1587275435_3.geometry} material={materials.mat23} />
          <mesh name="mesh1587275435_4" geometry={nodes.mesh1587275435_4.geometry} material={materials.mat12} />
          <mesh name="mesh1587275435_5" geometry={nodes.mesh1587275435_5.geometry} material={materials.mat17} />
          <mesh name="mesh1587275435_6" geometry={nodes.mesh1587275435_6.geometry} material={materials.mat15} />
        </group>
        <mesh name="group1607531193" geometry={nodes.group1607531193.geometry} material={materials.mat22} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1614000095" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1614000095" geometry={nodes.mesh1614000095.geometry} material={materials.mat20} />
          <mesh name="mesh1614000095_1" geometry={nodes.mesh1614000095_1.geometry} material={materials.mat21} />
          <mesh name="mesh1614000095_2" geometry={nodes.mesh1614000095_2.geometry} material={materials.mat9} />
        </group>
        <mesh name="group1614924645" geometry={nodes.group1614924645.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1630951219" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1630951219" geometry={nodes.mesh1630951219.geometry} material={materials.mat21} />
          <mesh name="mesh1630951219_1" geometry={nodes.mesh1630951219_1.geometry} material={materials.mat10} />
          <mesh name="mesh1630951219_2" geometry={nodes.mesh1630951219_2.geometry} material={materials.mat22} />
        </group>
        <group name="group1642498808" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1642498808" geometry={nodes.mesh1642498808.geometry} material={materials.mat21} />
          <mesh name="mesh1642498808_1" geometry={nodes.mesh1642498808_1.geometry} material={materials.mat17} />
        </group>
        <mesh name="group1652935550" geometry={nodes.group1652935550.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1660297908" geometry={nodes.group1660297908.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1663451856" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1663451856" geometry={nodes.mesh1663451856.geometry} material={materials.mat18} />
          <mesh name="mesh1663451856_1" geometry={nodes.mesh1663451856_1.geometry} material={materials.mat20} />
        </group>
        <group name="group1663536333" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1663536333" geometry={nodes.mesh1663536333.geometry} material={materials.mat21} />
          <mesh name="mesh1663536333_1" geometry={nodes.mesh1663536333_1.geometry} material={materials.mat17} />
          <mesh name="mesh1663536333_2" geometry={nodes.mesh1663536333_2.geometry} material={materials.mat22} />
          <mesh name="mesh1663536333_3" geometry={nodes.mesh1663536333_3.geometry} material={materials.mat16} />
          <mesh name="mesh1663536333_4" geometry={nodes.mesh1663536333_4.geometry} material={materials.mat23} />
        </group>
        <mesh name="group1677653859" geometry={nodes.group1677653859.geometry} material={materials.mat15} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1680125357" geometry={nodes.group1680125357.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1681713005" geometry={nodes.group1681713005.geometry} material={materials.mat15} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1710551366" geometry={nodes.group1710551366.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1712309893" geometry={nodes.group1712309893.geometry} material={materials.mat17} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1727640866" geometry={nodes.group1727640866.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1730822879" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1730822879" geometry={nodes.mesh1730822879.geometry} material={materials.mat23} />
          <mesh name="mesh1730822879_1" geometry={nodes.mesh1730822879_1.geometry} material={materials.mat12} />
        </group>
        <mesh name="group1785686067" geometry={nodes.group1785686067.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1797084705" geometry={nodes.group1797084705.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1805489611" geometry={nodes.group1805489611.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1808245208" geometry={nodes.group1808245208.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1810496948" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1810496948" geometry={nodes.mesh1810496948.geometry} material={materials.mat17} />
          <mesh name="mesh1810496948_1" geometry={nodes.mesh1810496948_1.geometry} material={materials.mat21} />
          <mesh name="mesh1810496948_2" geometry={nodes.mesh1810496948_2.geometry} material={materials.mat8} />
          <mesh name="mesh1810496948_3" geometry={nodes.mesh1810496948_3.geometry} material={materials.mat13} />
          <mesh name="mesh1810496948_4" geometry={nodes.mesh1810496948_4.geometry} material={materials.mat15} />
          <mesh name="mesh1810496948_5" geometry={nodes.mesh1810496948_5.geometry} material={materials.mat24} />
          <mesh name="mesh1810496948_6" geometry={nodes.mesh1810496948_6.geometry} material={materials.mat3} />
        </group>
        <group name="group1821365566" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1821365566" geometry={nodes.mesh1821365566.geometry} material={materials.mat21} />
          <mesh name="mesh1821365566_1" geometry={nodes.mesh1821365566_1.geometry} material={materials.mat22} />
          <mesh name="mesh1821365566_2" geometry={nodes.mesh1821365566_2.geometry} material={materials.mat13} />
          <mesh name="mesh1821365566_3" geometry={nodes.mesh1821365566_3.geometry} material={materials.mat23} />
          <mesh name="mesh1821365566_4" geometry={nodes.mesh1821365566_4.geometry} material={materials.mat12} />
          <mesh name="mesh1821365566_5" geometry={nodes.mesh1821365566_5.geometry} material={materials.mat20} />
        </group>
        <group name="group1837562763" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1837562763" geometry={nodes.mesh1837562763.geometry} material={materials.mat17} />
          <mesh name="mesh1837562763_1" geometry={nodes.mesh1837562763_1.geometry} material={materials.mat20} />
        </group>
        <mesh name="group1842026332" geometry={nodes.group1842026332.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1867135444" geometry={nodes.group1867135444.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1872015214" geometry={nodes.group1872015214.geometry} material={materials.mat13} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1874491697" geometry={nodes.group1874491697.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1883034995" geometry={nodes.group1883034995.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1888933330" geometry={nodes.group1888933330.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1891897442" geometry={nodes.group1891897442.geometry} material={materials.mat23} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1901927849" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1901927849" geometry={nodes.mesh1901927849.geometry} material={materials.mat21} />
          <mesh name="mesh1901927849_1" geometry={nodes.mesh1901927849_1.geometry} material={materials.mat22} />
        </group>
        <mesh name="group1903459864" geometry={nodes.group1903459864.geometry} material={materials.mat23} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1920833058" geometry={nodes.group1920833058.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1931019703" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1931019703" geometry={nodes.mesh1931019703.geometry} material={materials.mat20} />
          <mesh name="mesh1931019703_1" geometry={nodes.mesh1931019703_1.geometry} material={materials.mat13} />
          <mesh name="mesh1931019703_2" geometry={nodes.mesh1931019703_2.geometry} material={materials.mat21} />
        </group>
        <mesh name="group1936583362" geometry={nodes.group1936583362.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1954302538" geometry={nodes.group1954302538.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1955613170" geometry={nodes.group1955613170.geometry} material={materials.mat9} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1962927979" geometry={nodes.group1962927979.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1965775581" geometry={nodes.group1965775581.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1971286267" geometry={nodes.group1971286267.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group1974546850" geometry={nodes.group1974546850.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group1996662162" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1996662162" geometry={nodes.mesh1996662162.geometry} material={materials.mat20} />
          <mesh name="mesh1996662162_1" geometry={nodes.mesh1996662162_1.geometry} material={materials.mat21} />
          <mesh name="mesh1996662162_2" geometry={nodes.mesh1996662162_2.geometry} material={materials.mat9} />
        </group>
        <mesh name="group2002921704" geometry={nodes.group2002921704.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group2007915541" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh2007915541" geometry={nodes.mesh2007915541.geometry} material={materials.mat15} />
          <mesh name="mesh2007915541_1" geometry={nodes.mesh2007915541_1.geometry} material={materials.mat16} />
          <mesh name="mesh2007915541_2" geometry={nodes.mesh2007915541_2.geometry} material={materials.mat4} />
          <mesh name="mesh2007915541_3" geometry={nodes.mesh2007915541_3.geometry} material={materials.mat5} />
          <mesh name="mesh2007915541_4" geometry={nodes.mesh2007915541_4.geometry} material={materials.mat23} />
          <mesh name="mesh2007915541_5" geometry={nodes.mesh2007915541_5.geometry} material={materials.mat12} />
          <mesh name="mesh2007915541_6" geometry={nodes.mesh2007915541_6.geometry} material={materials.mat22} />
        </group>
        <mesh name="group2015198533" geometry={nodes.group2015198533.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group2033385218" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh2033385218" geometry={nodes.mesh2033385218.geometry} material={materials.mat17} />
          <mesh name="mesh2033385218_1" geometry={nodes.mesh2033385218_1.geometry} material={materials.mat20} />
        </group>
        <group name="group2039934188" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh2039934188" geometry={nodes.mesh2039934188.geometry} material={materials.mat22} />
          <mesh name="mesh2039934188_1" geometry={nodes.mesh2039934188_1.geometry} material={materials.mat21} />
        </group>
        <mesh name="group2051709799" geometry={nodes.group2051709799.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group2063525733" geometry={nodes.group2063525733.geometry} material={materials.mat15} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group2068977193" geometry={nodes.group2068977193.geometry} material={materials.mat21} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group2073665930" geometry={nodes.group2073665930.geometry} material={materials.mat22} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <mesh name="group2075169339" geometry={nodes.group2075169339.geometry} material={materials.mat17} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="group2089539604" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh2089539604" geometry={nodes.mesh2089539604.geometry} material={materials.mat22} />
          <mesh name="mesh2089539604_1" geometry={nodes.mesh2089539604_1.geometry} material={materials.mat23} />
          <mesh name="mesh2089539604_2" geometry={nodes.mesh2089539604_2.geometry} material={materials.mat12} />
          <mesh name="mesh2089539604_3" geometry={nodes.mesh2089539604_3.geometry} material={materials.mat16} />
          <mesh name="mesh2089539604_4" geometry={nodes.mesh2089539604_4.geometry} material={materials.mat4} />
          <mesh name="mesh2089539604_5" geometry={nodes.mesh2089539604_5.geometry} material={materials.mat5} />
          <mesh name="mesh2089539604_6" geometry={nodes.mesh2089539604_6.geometry} material={materials.mat15} />
        </group>
        <mesh name="group2134083659" geometry={nodes.group2134083659.geometry} material={materials.mat17} rotation={[-Math.PI, 0.167, -Math.PI]} />
        <group name="hotel" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh753123396" geometry={nodes.mesh753123396.geometry} material={materials.mat20} />
          <mesh name="mesh753123396_1" geometry={nodes.mesh753123396_1.geometry} material={materials.mat13} />
          <mesh name="mesh753123396_2" geometry={nodes.mesh753123396_2.geometry} material={materials.mat21} />
          <mesh name="mesh753123396_3" geometry={nodes.mesh753123396_3.geometry} material={materials.mat22} />
          <mesh name="mesh753123396_4" geometry={nodes.mesh753123396_4.geometry} material={materials.mat23} />
          <mesh name="mesh753123396_5" geometry={nodes.mesh753123396_5.geometry} material={materials.mat12} />
          <mesh name="mesh753123396_6" geometry={nodes.mesh753123396_6.geometry} material={materials.mat15} />
          {html && (
             <OverlayItem
             rotation-y={degToRad(180)}
             position-x={-1.2}
             position-y={0.8}
             position-z={-0.2}
             title={"Hotel"}
             description={"Go in Hotel"}
             button={"Explore Hotels"}
             bgColor={"bg-pink-500"}
             className={"transition delay-1000"}
             />
          )}
        </group>
        <group name="house" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh1185398696" geometry={nodes.mesh1185398696.geometry} material={materials.mat3} />
          <mesh name="mesh1185398696_1" geometry={nodes.mesh1185398696_1.geometry} material={materials.mat8} />
          <mesh name="mesh1185398696_2" geometry={nodes.mesh1185398696_2.geometry} material={materials.mat21} />
          <mesh name="mesh1185398696_3" geometry={nodes.mesh1185398696_3.geometry} material={materials.mat13} />
          <mesh name="mesh1185398696_4" geometry={nodes.mesh1185398696_4.geometry} material={materials.mat15} />
          <mesh name="mesh1185398696_5" geometry={nodes.mesh1185398696_5.geometry} material={materials.mat17} />
          <mesh name="mesh1185398696_6" geometry={nodes.mesh1185398696_6.geometry} material={materials.mat24} />
          {html && (
            <OverlayItem
            rotation-y={degToRad(180)}
            position-x={-0.6}
            position-z={-0.9}
            position-y={0.1}
            title={"House"}
            description={"Go in house"}
            button={"Explore Cabins"}
            bgColor={"bg-blue-800"}
            className={"transition delay-1000"}
            />
          )}
        </group>
        <group name="train" rotation={[-Math.PI, 0.167, -Math.PI]}>
          <mesh name="mesh382524841" geometry={nodes.mesh382524841.geometry} material={materials.mat16} />
          <mesh name="mesh382524841_1" geometry={nodes.mesh382524841_1.geometry} material={materials.mat4} />
          <mesh name="mesh382524841_2" geometry={nodes.mesh382524841_2.geometry} material={materials.mat5} />
          <mesh name="mesh382524841_3" geometry={nodes.mesh382524841_3.geometry} material={materials.mat15} />
          <mesh name="mesh382524841_4" geometry={nodes.mesh382524841_4.geometry} material={materials.mat23} />
          <mesh name="mesh382524841_5" geometry={nodes.mesh382524841_5.geometry} material={materials.mat12} />
          <mesh name="mesh382524841_6" geometry={nodes.mesh382524841_6.geometry} material={materials.mat22} />
          {html && (
            <OverlayItem
              rotation-y={degToRad(180)}
              position-x={-0.1}
              position-y={-0.2}
              position-z={-1.5}
              title={"Train"}
              description={"Go in train"}
              button={"Explore Destinations"}
              bgColor={"bg-green-800"}
              className={"transition delay-1000"}
            />
          )}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Winter.glb')
